// Env comes from worker-configuration.d.ts (generated by `wrangler types`, committed).
// This module adds the few helpers that read typed values out of it.

/** Messages on flaresend-send. `kind` lets the DLQ consumer tell queues apart. */
export interface SendQueueMessage {
  kind: "send";
  emailId: string;
  projectId: string;
  attempt: number;
}

/** Messages on flaresend-webhooks. */
export interface WebhookQueueMessage {
  kind: "webhook";
  deliveryId: string;
}

export const QUEUE_NAMES = {
  send: "flaresend-send",
  events: "flaresend-events",
  webhooks: "flaresend-webhooks",
  dlq: "flaresend-dlq",
} as const;

/** The mailer's Worker name (`name` in wrangler.jsonc), used to look up its own URLs in the Cloudflare API. */
export const MAILER_WORKER_NAME = "flaresend";

export function isProduction(env: Env): boolean {
  return (env.ENVIRONMENT as string) === "production";
}

export function broadcastMaxRecipients(env: Env): number {
  const n = Number(env.BROADCAST_MAX_RECIPIENTS);
  return Number.isFinite(n) && n > 0 ? n : 500;
}

export function publicBaseUrl(env: Env): string {
  const url = String(env.PUBLIC_BASE_URL);
  let end = url.length;
  while (end > 0 && url[end - 1] === "/") end--;
  return url.slice(0, end);
}

/** Lets callers hand background work to ctx.waitUntil when they have one, or await it otherwise. */
export type WaitUntil = (p: Promise<unknown>) => void;
